// <auto-generated />
using Discount.Grpc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Discount.Grpc.Migrations
{
    [DbContext(typeof(DiscountContext))]
    [Migration("20250318104525_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("Discount.Grpc.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Coupon");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 200,
                            Description = "Latest Apple iPhone",
                            ProductName = "iPhone X"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 150,
                            Description = "Flagship Samsung phone",
                            ProductName = "Samsung Galaxy S21"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 300,
                            Description = "Apple MacBook with M1 chip",
                            ProductName = "MacBook Pro"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 250,
                            Description = "Premium Windows laptop",
                            ProductName = "Dell XPS 13"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 100,
                            Description = "Noise-canceling headphones",
                            ProductName = "Sony WH-1000XM4"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 120,
                            Description = "Smartwatch with fitness tracking",
                            ProductName = "Apple Watch Series 7"
                        },
                        new
                        {
                            Id = 7,
                            Amount = 180,
                            Description = "Apple iPad with M1 chip",
                            ProductName = "iPad Pro"
                        },
                        new
                        {
                            Id = 8,
                            Amount = 90,
                            Description = "Popular gaming console",
                            ProductName = "Nintendo Switch"
                        },
                        new
                        {
                            Id = 9,
                            Amount = 80,
                            Description = "Bluetooth speaker with deep bass",
                            ProductName = "Bose SoundLink"
                        },
                        new
                        {
                            Id = 10,
                            Amount = 160,
                            Description = "Google's latest flagship phone",
                            ProductName = "Google Pixel 6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
